"""allow shipping address type

Revision ID: c199010157cb
Revises: 004_seed_roles_permissions
Create Date: 2026-02-12 15:10:10.998032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c199010157cb'
down_revision = '004_seed_roles_permissions'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_addresses_user'))
        batch_op.create_index(batch_op.f('ix_addresses_user_id'), ['user_id'], unique=False)
        # Update check constraint
        batch_op.drop_constraint('check_address_type', type_='check')
        batch_op.create_check_constraint('check_address_type', "type IN ('usa_locker', 'vzla_home', 'other', 'shipping')")

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cart_items_cart'))
        batch_op.create_index(batch_op.f('ix_cart_items_cart_id'), ['cart_id'], unique=False)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('carts_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_carts_user'))
        batch_op.create_index(batch_op.f('ix_carts_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_user'))
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_order_items_order'))
        batch_op.drop_index(batch_op.f('idx_order_items_store'))
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_store_id'), ['store_id'], unique=False)

    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_order_status_history_order'))
        batch_op.create_index(batch_op.f('ix_order_status_history_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_orders_created'))
        batch_op.drop_index(batch_op.f('idx_orders_number'))
        batch_op.drop_index(batch_op.f('idx_orders_status'))
        batch_op.drop_index(batch_op.f('idx_orders_user'))
        batch_op.drop_constraint(batch_op.f('orders_order_number_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_order'))
        batch_op.drop_index(batch_op.f('idx_payments_user'))
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('idx_permission_action'))
        batch_op.drop_index(batch_op.f('idx_permission_entity'))
        batch_op.create_index(batch_op.f('ix_permissions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_entity'), ['entity'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('idx_roles_name'))
        batch_op.drop_index(batch_op.f('idx_roles_type'))
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email_hash'))
        batch_op.drop_constraint(batch_op.f('users_email_hash_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email_hash'), ['email_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_hash'))
        batch_op.create_unique_constraint(batch_op.f('users_email_hash_key'), ['email_hash'])
        batch_op.create_index(batch_op.f('idx_users_email_hash'), ['email_hash'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.create_index(batch_op.f('idx_roles_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('idx_roles_name'), ['name'], unique=True)
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_entity'))
        batch_op.drop_index(batch_op.f('ix_permissions_action'))
        batch_op.create_index(batch_op.f('idx_permission_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('idx_permission_action'), ['action'], unique=False)
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.create_index(batch_op.f('idx_payments_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_order'), ['order_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))
        batch_op.create_unique_constraint(batch_op.f('orders_order_number_key'), ['order_number'])
        batch_op.create_index(batch_op.f('idx_orders_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_number'), ['order_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_created'), ['created_at'], unique=False)

    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_history_order_id'))
        batch_op.create_index(batch_op.f('idx_order_status_history_order'), ['order_id'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_store_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.create_index(batch_op.f('idx_order_items_store'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_items_order'), ['order_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.create_index(batch_op.f('idx_notifications_user'), ['user_id'], unique=False)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carts_user_id'))
        batch_op.create_index(batch_op.f('idx_carts_user'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('carts_user_id_key'), ['user_id'])

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_cart_id'))
        batch_op.create_index(batch_op.f('idx_cart_items_cart'), ['cart_id'], unique=False)

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_user_id'))
        batch_op.create_index(batch_op.f('idx_addresses_user'), ['user_id'], unique=False)
        # Revert check constraint
        batch_op.drop_constraint('check_address_type', type_='check')
        batch_op.create_check_constraint('check_address_type', "type IN ('usa_locker', 'vzla_home', 'other')")

    # ### end Alembic commands ###
